### ISSUE TITLE
assets.yml regex is silently ignored

### ISSUE THREAD

**Issue by madamkiwi** [pivotal-cf/kiln#20]
This causes it to download the latest versions of all the assets when doing a `kiln fetch`, but then removes any where the sha does not match. It's very unclear why it's happening from an end user perspective.

@jpalermo && @madamkiwi

**Comment by mcwumbly** [comment]
This issue was introduced when we made [this change](https://github.com/pivotal-cf/kiln/pull/17). 

We currently compile BOSH releases for different versions of PAS and put them in separate subdirectories within a single S3 bucket. So "release foo" compiled for "stemcell v77" can be compiled for PAS 2.6 and PAS 2.7 and end up in `/2.6/foo-release-stemcell-77.tgz` and `/2.7/foo-release-stemcell-77.tgz` 

At the time, we assumed that a given release compiled against the same stemcell were equivalent, and that it wouldn't matter which one got downloaded.

But we failed to consider the fact that the SHAs could be different, and that kiln would delete the ones that do not match.

That's a pain.

In the future, we _do_ hope to be able to compile releases for a given stemcell _once_ and store those in a PAS-version-agnostic place. But until that time, it may be best to revert the earlier change.

In the meantime, can you work around this issue by using kiln version `0.20.0`?

**Comment by mcwumbly** [comment]
I caught up with @syslxg who ran into this issue earlier and we agreed that we should just revert the earlier changes for now, which was done here: https://github.com/pivotal-cf/kiln/commit/c7ea17e15b6c649cd07b012592e59d76d227dfd3

I'll create a follow-up issue track the desire to remove the regex once it's safe to do so.
